version: "3.9"
volumes:
  grafana_storage:
  prometheus_conf:
  prometheus_data:
networks:
  stat-net:
    driver: bridge
services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "192.168.42.3:9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/host/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /:/host/rootfs:ro
      - /sys:/host/sys:ro
    networks:
      - stat-net
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel 
  prometheus:
    image: prom/prometheus:latest
    expose:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - prometheus_conf:/etc/prometheus:ro
      - prometheus_data:/prometheus
    networks:
      - stat-net
    extra_hosts:
      - "cacheserver1:192.168.42.2"
      - "gameserver1:192.168.42.3"
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "192.168.42.3:3000:3000"
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - stat-net
    extra_hosts:
      - "cacheserver1:192.168.42.2"
      - "gameserver1:192.168.42.3"
