{
 "title": "Daniel dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "game_node",
    "label": "Gameserver host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$game_job\"}, instance)"
    }
   },
   {
    "name": "cache_node",
    "label": "Cacheserver node:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$cache_job\"}, instance)"
    }
   },
   {
    "name": "cache_job",
    "label": "Cache job:",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "game_job",
    "label": "Game job:",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cacheserver - RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$cache_node\",job=\"$cache_job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$cache_node\",job=\"$cache_job\"})"
    }
   ]
  },
  {
   "title": "Cacheserver - Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$cache_node\",job=\"$cache_job\"}) /  count(count(node_cpu_seconds_total{instance=\"$cache_node\",job=\"$cache_job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Cacheserver - Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$cache_node\",job=\"$cache_job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$cache_node\",job=\"$cache_job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Cacheserver - Tank FS Used",
   "type": "gauge",
   "description": "Used Tank FS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$cache_node\",job=\"$cache_job\",mountpoint=\"/tank\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$cache_node\",job=\"$cache_job\",mountpoint=\"/tank\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Gameserver - RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$game_node\",job=\"$game_job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$game_node\",job=\"$game_job\"})"
    }
   ]
  },
  {
   "title": "Gameserver - Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$game_node\",job=\"$game_job\"}) /  count(count(node_cpu_seconds_total{instance=\"$game_node\",job=\"$game_job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Gameserver - Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$game_node\",job=\"$game_job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$game_node\",job=\"$game_job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Gameserver - Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$game_node\",job=\"$game_job\"} - node_boot_time_seconds{instance=\"$game_node\",job=\"$game_job\"}"
    }
   ]
  },
  {
   "title": "Cacheserver - Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$cache_node\",job=\"$cache_job\"} - node_boot_time_seconds{instance=\"$cache_node\",job=\"$cache_job\"}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$game_node\",job=\"$game_job\"} - node_memory_MemFree_bytes{instance=\"$game_node\",job=\"$game_job\"} - (node_memory_Cached_bytes{instance=\"$game_node\",job=\"$game_job\"} + node_memory_Buffers_bytes{instance=\"$game_node\",job=\"$game_job\"} + node_memory_SReclaimable_bytes{instance=\"$game_node\",job=\"$game_job\"})",
     "legendFormat": "Gameserver"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$cache_node\",job=\"$cache_job\"} - node_memory_MemFree_bytes{instance=\"$cache_node\",job=\"$cache_job\"} - (node_memory_Cached_bytes{instance=\"$cache_node\",job=\"$cache_job\"} + node_memory_Buffers_bytes{instance=\"$cache_node\",job=\"$cache_job\"} + node_memory_SReclaimable_bytes{instance=\"$cache_node\",job=\"$cache_job\"})",
     "legendFormat": "Cacheserver"
    }
   ]
  },
  {
   "title": "CPU [system]",
   "type": "timeseries",
   "description": "CPU for alle computere",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Cacheserver ...42.2"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])) * 100",
     "legendFormat": "Gameserver ...42.3"
    }
   ]
  },
  {
   "title": "TCP In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "Cacheserver - InSegs - Segments received"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "Gameserver - InSegs - Segments received"
    }
   ]
  },
  {
   "title": "TCP Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "Cacheserver - OutSegs - Segments sent"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "Gameserver - OutSegs - Segments sent"
    }
   ]
  },
  {
   "title": "UDP In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "Cacheserver - InDatagrams - Datagrams received"
    },
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "Gameserver - InDatagrams - Datagrams received"
    }
   ]
  },
  {
   "title": "UDP Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "Cacheserver - OutDatagrams - Datagrams sent"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "Gameserver - OutDatagrams - Datagrams sent"
    }
   ]
  },
  { "title": "Gameserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "TCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "OutRsts - Segments sent with RST flag"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_NoPorts{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "rate(node_netstat_UdpLite_InErrors{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "rate(node_netstat_Udp_SndbufErrors{instance=\"$game_node\",job=\"$game_job\"}[$__rate_interval])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  },
  { "title": "Cacheserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "TCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
    },
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "OutRsts - Segments sent with RST flag"
    }
   ]
  },
  {
   "title": "UDP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_NoPorts{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
    },
    {
     "expr": "rate(node_netstat_UdpLite_InErrors{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received"
    },
    {
     "expr": "rate(node_netstat_Udp_SndbufErrors{instance=\"$cache_node\",job=\"$cache_job\"}[$__rate_interval])",
     "legendFormat": "SndbufErrors - UDP buffer errors send"
    }
   ]
  }
 ]
}