global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "gameserver-node"
    scrape_interval: 7s
    static_configs:
    - targets: ["192.168.42.3:9100"]

  - job_name: "cacheserver-node"
    scrape_interval: 7s
    static_configs:
    - targets: ["192.168.42.2:9100"]

remote_write:
    - url: "grafana"
