version: '2'
services:
  #dns:
  #  image: lancachenet/lancache-dns:latest
  #  environment:
  #    USE_GENERIC_CACHE: true
  #    LANCACHE_IP: ${LANCACHE_IP}
  #    DNS_BIND_IP: ${DNS_BIND_IP}
  #    UPSTREAM_DNS: ${UPSTREAM_DNS}
  #    TZ: ${TZ}
  #  restart: unless-stopped
  #  ports:
  #    - ${DNS_BIND_IP}:53:53/udp
  #    - ${DNS_BIND_IP}:53:53/tcp
  #  network_mode: "host"
  monolithic:
    image: lancachenet/monolithic:latest
    environment:
      CACHE_ROOT: ${CACHE_ROOT}
      CACHE_DISK_SIZE: ${CACHE_DISK_SIZE}
      CACHE_INDEX_SIZE: ${CACHE_INDEX_SIZE}
      CACHE_MAX_AGE: ${CACHE_MAX_AGE}
      UPSTREAM_DNS: ${UPSTREAM_DNS}
      TZ: ${TZ}
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    network_mode: "host"
